### ISSUE TITLE
doesnt work on blender 3.4.1at all, tons and tons of errors is this not supported anymore?

### ISSUE THREAD

**Issue by DayZcustomMods** [AlwarrenSidh/ArmAToolbox#41]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\Unite\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\ArmaToolbox\__init__.py", line 24, in <module>
    from MDLImporter import importMDL
  File "C:\Users\Unite\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\ArmaToolbox\..\ArmaToolbox\MDLImporter.py", line 14, in <module>
    import ArmaTools
  File "C:\Users\Unite\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\ArmaTools.py", line 9, in <module>
    from ArmaProxy import RebaseProxies, GetMaxProxy
ImportError: cannot import name 'RebaseProxies' from 'ArmaProxy' (C:\Users\Unite\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\ArmaToolbox\..\ArmaToolbox\ArmaProxy.py)

**Comment by Vladimir8911** [comment]
тоже не работает

**Comment by AlwarrenSidh** [comment]
English only please

**Comment by faerla** [comment]
having the same issue, was this caused by a Blender update? I'm way out of my depth here

**Comment by sutuliy-dog** [comment]
Guys, using 3.0.4 version of this plugin for aboit half a year (since blender 3.3 i think, cant remember) and ever since had no issues. Works fine on the current version of Blender 3.6.

Im modding dayz, not arma, but only difference is location of O2 script. 

You need to link path to it in the plugin settings after installation, make sure you did it. I remember having issues with import/export, until i linked this script to plugin.
![image](https://github.com/AlwarrenSidh/ArmAToolbox/assets/103241422/1f424f68-05b2-4a44-95b1-9c955eee78c3)
